language: node_js
node_js:
  - 10

services:
  - docker 

script: 
  - docker build -t react-example:latest .
  - docker images

env:
  global:
    - secure: ewogICJ0eXBlIjogInNlcnZpY2VfYWNjb3VudCIsCiAgInByb2plY3RfaWQiOiAia2NzLWFjZTIi
LAogICJwcml2YXRlX2tleV9pZCI6ICI0ZDY1YjA1MjczMzMzMDIyZjg1MjFlMDE3Yjk2YWFkM2Vl
MmQ1MTViIiwKICAicHJpdmF0ZV9rZXkiOiAiLS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tXG5N
SUlFdkFJQkFEQU5CZ2txaGtpRzl3MEJBUUVGQUFTQ0JLWXdnZ1NpQWdFQUFvSUJBUUN2N2F4SU5B
Mkl6aUZyXG5RSEk5TkcwNDViWGtLNmZTdnJrZ1FKWGFLejB5cEczZUJWWEM3UXloR3VRd2V0QXNv
WW9wUm45c1AveTFOa2R2XG5SZXN1TjU4T29vT1dZQ3lBeW1XYWlaUmQzWW5QVVlxRk9LNTJNa2dz
bzZzYTlqclNFUzJrSnFtNXhpY2ZMRUFqXG5qWEFFUzRHTmdJcnVad0tkZGpYb2Nlbjc4TE41aTRv
aUFqcmZVdWZvd2orNDhrejNmeHhJbVd3dnlaSTdqN0RwXG5PMlduTVA1aklRVWg2RHo2aURpUzE5
dUNUVEpPTVcrOEE1ZUZXUGtYTkdRYmdvR2pvWHpiSnJ0eTMzQXMycVhzXG4wd3Y5Y0ltVVZIb3ZX
KzdiaXhTOHQ3TElKdjZFcG9zbDBQNzY0NEZ0ZVR4V1NWRkNzUm80WjQ1SkViVDVFNUY0XG5nMHNx
UXRKWEFnTUJBQUVDZ2dFQUxPWkZyKy9JL0g5UFBDWW9nY0pkbGNYYWxDOG9GN3NoV0QvamZ0akdO
NlNMXG5mYnh5MU5yVy9FNzJxZ0RPSEhYbDR2N2hDbW1TUDFWcENkY1lYS1ZKYk56QkpLSEsrZHV0
N3JEcU1zS1ZwMW15XG5OcW51cksvTWg4Z0ZwVTN1V1NxVk1XM0VwMnNSRlAyZ0tQS3lBZ2FiTzlm
d25VT2hBVHJvS3pqWGRMdExzdHNqXG5pcGtnZGdjaWlIQnhoaGdNVUJPVzZDeFgxRXB1SGZxT01v
YjNDb1hYcTF0aTgvcVFrLzV6eUs2T0xQT0w5SmxiXG5Uc3E1MWxoajRMQ3FVWFNRWXRlY0doTkts
WTJTMzBwdllMU3YrS1kzeWxTdDFTaWRjaGo0aThjYWVzR2FlMExHXG55b2NvYjRhZjd5NDFzaTgv
bmI1Rzg5RExPQXB2bDMwMHE0eCtWRkNiRVFLQmdRRGlaaGhIUFlpclExQlJ5MEpKXG5pTmlWcmxB
ZERnTVE3VkViSWVkWDJ6d3hHODNoak1EMVJ3amNQaXF1ZE9VelU0RzRNYzF6aStEejJZNUdrWFF6
XG5oUUxGS0ZRcGNweWgrTkFxazNMb1FBWVlyTUZzNUIrc29YaDBnS09XZVV5dW8zcDVtcmp1QnJw
RHBleTIwWUd2XG50ZkoraTkzamRlQkZBVFlqcmRaNzJMcG5iUUtCZ1FERzdrSS9qMjMzZU15Wmpt
Ym9ka1l0aHpvb0Y5cDg1REtWXG5OZ2ZXeSttQTRzQmF1UWwwMkFnQy9ZMWpmSDkxOWtuM294a0ZF
bEpONVJVM3pUdkxxaDFQY1RPb2pHVlVCWDMvXG5ZenMyWEk5Q1plWWd0Q25DcU9pdDBJUkx5YkdN
d0c0QS9sQ1BOcmxPR1NBRnphNUp4ZFgwSTI5VGNzWVBQUkIwXG5lK1VpMENBeVV3S0JnSElZaWJ1
OVl4Y01nWG4zT1p6ZGZtbFF3OGNndktMWE5yeTV4V0VkZDZRNEl2VzhmYkllXG43blF3VUVwRFZ3
OGEwcEVGYUVrSEFZTmk3TFRic1BnVjNHT0lBNEl2NUlnc1lKeFVXdUI1QTVtRDFxY09BSGg3XG5s
N3orNTNKNkJ3OHNEQmtreEhZUXBlWlp4SVlONTVHcDNGK3lGVTBBcHRtZjFxejhlczlIVmdteEFv
R0FiN29SXG5hekZiU2NxRzN4ZWpwSndJL2prYzZMZTg5cmdUME1udnpTdnBrWUhKRnlzbHJJSkl2
YVU2YTgzWXFLQVRHd3AzXG5XdW5YWC9oeDJrMWljQml6TFpNZXVHTmg1YmJQOVVmK1VhSGF0Q2dX
Ly9jd0hTeFF3bzZDUHk2Z2tiVGlFNXpDXG5FaTFpRmdMMmdVdnJ2M05sbnlEbnZhNlFucTVsTjRi
K1FuY3lIaEVDZ1lCSmhzcVlZUnNOUWcyWmd4N1NuVCs0XG5LUXVnZGRFcTJkeEQ0N002WDdONEpa
UUpZbm9IVmpJcXIwTk5PcmFvR1JTTC9zUGhqQnlLeUVyMURDZmtiWmlsXG5WVHRTUzdKMElPQnRQ
VGlMaWhJbTluditJR1pzUCtYSE5GaWZWQWdwcy9mVWJMR1BmWjVRNHZyTmUxTmsrU0hLXG5MZkcy
aTkwRHN3TGo5a3UwbXJNWERnPT1cbi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS1cbiIsCiAgImNs
aWVudF9lbWFpbCI6ICJ0cmF2aXMtdHJhdmlzLXRlc3Qtd2l0aC1nYXJAa2NzLWFjZTIuaWFtLmdz
ZXJ2aWNlYWNjb3VudC5jb20iLAogICJjbGllbnRfaWQiOiAiMTAxMjAxMTI2MDM0MzEzODIzMDI4
IiwKICAiYXV0aF91cmkiOiAiaHR0cHM6Ly9hY2NvdW50cy5nb29nbGUuY29tL28vb2F1dGgyL2F1
dGgiLAogICJ0b2tlbl91cmkiOiAiaHR0cHM6Ly9vYXV0aDIuZ29vZ2xlYXBpcy5jb20vdG9rZW4i
LAogICJhdXRoX3Byb3ZpZGVyX3g1MDlfY2VydF91cmwiOiAiaHR0cHM6Ly93d3cuZ29vZ2xlYXBp
cy5jb20vb2F1dGgyL3YxL2NlcnRzIiwKICAiY2xpZW50X3g1MDlfY2VydF91cmwiOiAiaHR0cHM6
Ly93d3cuZ29vZ2xlYXBpcy5jb20vcm9ib3QvdjEvbWV0YWRhdGEveDUwOS90cmF2aXMtdHJhdmlz
LXRlc3Qtd2l0aC1nYXIlNDBrY3MtYWNlMi5pYW0uZ3NlcnZpY2VhY2NvdW50LmNvbSIKfQo=

deploy: 
  provider: script 
  script:
    - export TRAVIS_TEST_WITH_GAR_REPO=us-west1-docker.pkg.dev/kcs-ace2/travis-test-with-gar/travis-image
    - docker build -f Dockerfile -t $TRAVIS_TEST_WITH_GAR_REPO:build-$TRAVIS_BUILD_NUMBER -t $TRAVIS_TEST_WITH_GAR_REPO:latest .
    - docker push $TRAVIS_TEST_WITH_GAR_REPO:build-$TRAVIS_BUILD_NUMBER
    - docker push $TRAVIS_TEST_WITH_GAR_REPO:latest
  on:
    branch: main
