language: node_js
node_js:
  - 10

services:
  - docker 

script: 
  - docker build -t react-example:latest .
  - docker images 

deploy: 
  provider: script 
  script:
    - echo "$ARTIFACT_REGISTRY_KEY" | docker login -u _json_key_base64 --password-stdin https://us-west1-docker.pkg.dev
    - export GCR=gcr.io/kcs-ace2/hello-node/travis-image
    - docker tag react-example gcr.io/kcs-ace2/hello-node/travis-image:latest
    - docker gcr.io/kcs-ace2/hello-node/travis-image
  on:
    branch: main
