#!/bin/bash
echo "$ARTIFACT_REGISTRY_KEY" | docker login -u _json_key_base64 --password-stdin https://us-west1-docker.pkg.dev
docker tag react-example us-west1-docker.pkg.dev/kcs-ace2/samplejava/travis-test-1:latest
docker push us-west1-docker.pkg.dev/kcs-ace2/samplejava/travis-test-1